Avoid error from tsc when running locally.
src/__tests__/nodeVersion.tsx:5:33 - error TS2339: Property 'version' does not exist on type 'typeof process'.

Didn't get this error on CI, it's not clear why not.